### PR TITLE
Allow several connection parameters to be NULL

### PR DESCRIPTION
**Pull request by peternowee**
With the port to Rcpp/C++ (starting with commit b74b697396), the
default value for several parameters of the `dbConnect()` method
changed from `NULL` to `""`. This was probably necessary because a
C++ `std::string` cannot be `NULL`. However, the MySQL C API function
`mysql_real_connect` does accept `NULL` and even requires it for a
password to be read from an option file:

> Then, in the `mysql_real_connect()` call, specify the “no-value”
> value for each parameter to be read from an option file:
With the port to Rcpp/C++ (starting with commit b74b697396), the
default value for several parameters of the `dbConnect()` method
changed from `NULL` to `""`. This was probably necessary because a
C++ `std::string` cannot be `NULL`. However, the MySQL C API function
`mysql_real_connect` does accept `NULL` and even requires it for a
password to be read from an option file:

> Then, in the `mysql_real_connect()` call, specify the “no-value”
> value for each parameter to be read from an option file:
> [..]
> - For `passwd`, specify a value of `NULL`. (For the password, a
> value of the empty string in the `mysql_real_connect()` call cannot
> be overridden in an option file, because the empty string indicates
> explicitly that the MySQL account must have an empty password.)
>
> -- [MySQL 5.7 Reference Manual, 22.8.7.54 mysql_real_connect()]
> (https://dev.mysql.com/doc/refman/5.7/en/mysql-real-connect.html)

This patch will again allow `NULL` as an argument for `dbname`,
`username`, `password`, `host`, `unix.socket`, `groups` and
`default.file`. Except for `groups`, which defaults to `"rs-dbi"`,
the default values of these parameters will also be `NULL` again.

This is accomplished by wrapping the `std::string` in the recently
introduced `Rcpp::Nullable` class and checking for `isNull()` in the
call to the MySQL C code.

Because of the use of `Rcpp::Nullable`, the Rcpp dependency now has
a version requirement (>=0.12.4).

Fixes rstats-db/RMySQL#55

### CODE REVIEW

**Comment by peternowee** [comment]
@krlmlr It was [not possible for me to do a pull request for a new upstream branch][1]. See [how to merge a PR into another branch][2].

[1]: http://stackoverflow.com/questions/9796370/github-pull-request-to-a-new-upstream-branch
[2]: http://stackoverflow.com/questions/9135913/merge-pull-request-to-a-different-branch-than-default-in-github

**Comment by peternowee** [comment]
Travis CI build probably failed because of the Rcpp version requirement (>= 0.12.4). See commit 20d242d for details.

**Comment by krlmlr** [comment]
Thanks, this is just fine. I'll pull in the first commit manually and then let this PR wait until Rcpp 0.12.4 becomes available.

**Comment by krlmlr** [comment]
Rcpp 0.12.4 is out now. Could you please merge with master?

**Comment by peternowee** [comment]
Ok, I merged with master, rebuilt and tested. Everything still seems to be ok. I also ran the automated tests:

    > devtools::test(pkg = "~/Development/R-git/RMySQL")
    Loading RMySQL
    Testing RMySQL
    DBItest: Getting started: .....
    DBItest: Driver: .............................S...S..
    DBItest: Connection: ..S......................................................................................................S..
    DBItest: Result: ...S..................................................................S....S...........................................................................................................SSSSSS.....SSSSSSSSS.....................................................SSSSSSSSSSSSSSS
    DBItest: SQL: S...........S................................................S...S......SS......SSSS....S...
    DBItest: Metadata: .......................................SS.S............S......S......SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
    DBItest: Full compliance: SS
    dbWriteTable: ..
    queries: .

All skips (`S`) were `by request`.

Let me know if you prefer a rebase instead of a merge.

**Comment by krlmlr** [comment]
Thanks!

**Comment by peternowee** [comment]
You too, I see you have been doing a lot recently!

**Pull request merged**
