### PR TITLE
Add TAGS file to .gitignore

### PR DESCRIPTION
**Pull request by sambrightman**

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. What's the motivation for this PR?

**Comment by sambrightman** [comment]
To avoid accidentally committing etags output when editing with emacs.

**Comment by krlmlr** [comment]
Could you use [`.git/info/exclude`](http://stackoverflow.com/a/1753078/946850) or even a [global ignore file](http://stackoverflow.com/a/7335487/946850) for this? I'm not sure this is universally useful, and you probably wouldn't want to submit a PR like this to all repos you're contributing to.

**Comment by sambrightman** [comment]
Yes, I'm sure they would work. Where I am it is fairly normal to add common editor/IDE files to the .gitignore. Your choice.

**Comment by krlmlr** [comment]
I don't mind having this, but this is the first time I've ever heard of a `TAGS` file.

**Pull request merged**
