### PR TITLE
Connection info and slots

### PR DESCRIPTION
**Pull request by peternowee**
`MySQLConnection` class slots `host` and `db` were filled with the
`host` and `dbname` arguments passed to `dbConnect()`. However, these
values may be `NULL` when using an option file.

With this patch, the slots will be filled with the values of `host`
and `db` members of the MySQL C API's MYSQL struct created by the
actual connection.

To accomplish the above, another change was necessary:

This change makes the list returned by `dbGetInfo()` more consistent
with that of the current stable version (RMySQL 0.10.7).

Notes:
- The value of `dbGetInfo()$host` has now changed (back to how it was
  in 0.10.7).
- `dbGetInfo()$rsId` (existing under 0.10.7) has not been implemented
  yet.

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks! It looks like #134 conflicts with this PR, could you please take a look?

**Comment by peternowee** [comment]
Yes, it should be ok now, thanks!

**Comment by krlmlr** [comment]
Could you please merge master once again? I'm not sure why the conflicts keep popping up.

Please note that there seem to be some failures with the Travis tests.

**Comment by peternowee** [comment]
The conflict was with your commit f676e19 (wrap mysql_() output in std::string), which edited some of the same code. I solved it by also wrapping my changes in `std::string` where appropriate.

I tested manually and also ran the automated test. Two tests fail:
````
1. Failure: DBItest: stress_load_unload ----------------------------------------
system(...) not equal to 0.
1/1 mismatches
[1] 1 - 0 == 1


2. Failure: DBItest: stress_load_connect_unload --------------------------------
system(...) not equal to 0.
1/1 mismatches
[1] 1 - 0 == 1
````
However, these two tests also fail on master now in my setup.

All these merges and conflicts have made this PR a bit messy, so just let me know if you would like me to rebase. I can do that in a clean, new branch and PR, so as not to change the history of this one.

**Comment by peternowee** [comment]
Hang on, something is not working it seems.

**Comment by peternowee** [comment]
No, sorry, everything is working fine.

(I got an error as a result of not cleaning up build objects before rebuilding from another branch.)

**Comment by peternowee** [comment]
Two other notes:
- After these changes the field names returned by `dbGetInfo()` on an RMySQL connection do not fully comply with those defined in `?dbGetInfo` (part of DBI). However, this was already not the case in RMySQL 0.10.7, nor in 0.11-2. I think compliance with the definition in `?dbGetInfo` should be considered a separate issue, similar to issue rstats-db/RSQLite#117 in RSQLite.
- Just to clarify: [NEWS for RMySQL 0.11-1 (2016-03-24)][1] reports:
> - dbGetInfo() has been removed. Please use the individual metadata functions.
However, `dbGetInfo(con)` still works. Commit 89524ea only removed `dbGetInfo()` on MySQL result sets.
[1]: https://github.com/rstats-db/RMySQL/blob/master/NEWS.md

**Comment by krlmlr** [comment]
Thanks!

**Pull request merged**
